### PR TITLE
update golang.org/x/net to latest version

### PR DESCRIPTION
**Pull request by rkolp**

### CODE REVIEW

**Comment by bhcleek** [comment]
You should probably remove my membership; I can still review and I get notifications for this

**Review by seikenberry9 — APPROVED** [review]
LGTM

**Comment by rkolp** [comment]
> You should probably remove my membership; I can still review and I get notifications for this

Will do, thanks @bhcleek!

**Review by leyla-kose — APPROVED** [review]

**Comment by sweetnickyc** [comment]
hi @bhcleek !

**Comment by bhcleek** [comment]
Hey, @sweetnickyc ! Let's s grab lunch soon

**Pull request merged**
